In [171]:
%ls

Specification.pdf         model.h5                  requirements.txt
Untitled.ipynb            processed.cleveland.data  venv/


In [214]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model

In [192]:
df = pd.read_csv('processed.cleveland.data')
# df['thal'] = df['thal'].astype(int)
df = df.replace('?', np.nan).dropna()
df['ca'] = df['ca'].astype(float)
df['thal'] = df['thal'].astype(float)
df['thal'] = df['thal'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 297 entries, 0 to 301
Data columns (total 14 columns):
age         297 non-null float64
sex         297 non-null float64
cp          297 non-null float64
trestbps    297 non-null float64
chol        297 non-null float64
fbs         297 non-null float64
restecg     297 non-null float64
thalach     297 non-null float64
exang       297 non-null float64
oldpeak     297 non-null float64
slope       297 non-null float64
ca          297 non-null float64
thal        297 non-null int64
target      297 non-null int64
dtypes: float64(12), int64(2)
memory usage: 34.8 KB


In [193]:
df.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca  thal  target  
0    3.0  0.0     6       0  
1    2.0  3.0     3       2  
2    2.0  2.0     7       1  
3    3.0  0.0     3       0  
4    1.0  0.0     3       0

In [194]:
target = df.pop('thal')

In [201]:
target.unique()

array([6, 3, 7])

In [202]:
target[target == 3] = 0
target[target == 6] = 1
target[target == 7] = 2

In [203]:
cat_target = to_categorical(target, num_classes=3)
cat_target

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0

In [204]:
df = df.drop('target', axis=1)

In [205]:
def build_model():
    model = keras.Sequential([
        layers.Dense(128, activation=tf.nn.relu, input_shape=[len(df.keys())]),
        layers.Dropout(0.5),
        layers.Dense(128, activation=tf.nn.relu),
        layers.Dense(3, activation=tf.nn.softmax),
    ])
    
    optimiser = tf.keras.optimizers.RMSprop(0.001)
#     optimiser = tf.keras.optimizers.Adam(0.001)
    
    model.compile(loss='categorical_crossentropy',
                optimizer=optimiser,
                metrics=['mean_squared_error', 'accuracy'])
    
    
    return model

In [206]:
model = build_model()

In [207]:
EPOCHS = 10000

history = model.fit(df, cat_target, epochs=EPOCHS, validation_split=0.2, verbose=0)

In [208]:
hist = pd.DataFrame(history.history)
hist

loss  mean_squared_error       acc  val_loss  \
0     6.806302            0.300643  0.540084  7.253143   
1     7.119438            0.300644  0.548523  7.253144   
2     7.346628            0.307362  0.535865  7.253143   
3     6.878185            0.310674  0.531646  3.803544   
4     6.743667            0.304236  0.535865  6.208878   
5     6.432106            0.314111  0.518987  7.530315   
6     7.074227            0.328336  0.502110  6.478799   
7     6.242369            0.309168  0.514768  7.082781   
8     6.941294            0.311012  0.527426  7.157105   
9     7.068628            0.323387  0.510549  5.957770   
10    6.603871            0.311851  0.531646  4.806841   
11    6.822904            0.320728  0.514768  7.155820   
12    6.159463            0.287098  0.561181  5.788769   
13    6.821955            0.326463  0.497890  7.157642   
14    6.505633            0.293870  0.548523  5.233822   
15    6.862954            0.313191  0.518987  7.200423   
16    5.983137            0.286719  0.561181  7.153943   
17    5.977167            0.290296  0.552743  4.916890   
18    6.305224            0.312427  0.523207  5.854581   
19    6.447008            0.307184  0.531646  4.891907   
20    5.968359            0.305412  0.527426  5.049814   
21    6.044549            0.291223  0.556962  9.850767   
22    6.061755            0.297700  0.544304  6.187120   
23    5.463823            0.289186  0.556962  5.963246   
24    6.315095            0.294964  0.548523  7.014785   
25    6.099082            0.285967  0.565401  7.039296   
26    5.832771            0.280581  0.569620  5.313891   
27    5.824689            0.300134  0.544304  6.436337   
28    5.631742            0.268139  0.590717  6.715652   
29    5.433523            0.278276  0.565401  7.476463   
...        ...                 ...       ...       ...   
9970  0.304697            0.062619  0.869198  2.683356   
9971  0.264651            0.050837  0.898734  2.580862   
9972  0.314455            0.059396  0.890295  2.728109   
9973  0.263855            0.053904  0.881857  2.553054   
9974  0.427295            0.079597  0.827004  2.589232   
9975  0.311448            0.061258  0.877637  2.530163   
9976  0.395985            0.073461  0.848101  2.602186   
9977  0.328674            0.068279  0.852321  2.748852   
9978  0.279978            0.054162  0.890295  2.383276   
9979  0.325799            0.060349  0.864979  2.271387   
9980  0.387450            0.060101  0.864979  2.441880   
9981  0.255075            0.052098  0.894515  2.613049   
9982  0.335972            0.071970  0.843882  2.440475   
9983  0.348054            0.058750  0.890295  2.664073   
9984  0.248010            0.047315  0.902954  2.542514   
9985  0.312309            0.060316  0.869198  2.493080   
9986  0.271719            0.052995  0.886076  2.678851   
9987  0.361186            0.063781  0.860759  2.294872   
9988  0.286022            0.055119  0.886076  2.591904   
9989  0.305990            0.052532  0.919831  2.658396   
9990  0.328309            0.058431  0.877637  2.552202   
9991  0.285634            0.050337  0.902954  2.637677   
9992  0.244841            0.051728  0.886076  2.754249   
9993  0.311939            0.057879  0.890295  2.662900   
9994  0.490312            0.061420  0.881857  2.997818   
9995  0.972539            0.086461  0.839662  2.859561   
9996  0.583601            0.080757  0.848101  2.250614   
9997  0.412710            0.072251  0.848101  2.379308   
9998  0.212241            0.041901  0.911392  2.512796   
9999  0.278788            0.051539  0.894515  2.372209   

      val_mean_squared_error   val_acc  
0                   0.300000  0.550000  
1                   0.300000  0.550000  
2                   0.300000  0.550000  
3                   0.317818  0.466667  
4                   0.290849  0.566667  
5                   0.432732  0.333333  
6                   0.298680  0.550000  
7                   0.299953  0.550000  
8                   0.299999  0.550000  
9  

In [209]:
model.predict(df[:10]).argmax(axis=1)

array([2, 0, 2, 0, 0, 0, 0, 0, 2, 0])

In [210]:
cat_target[:10].argmax(axis=1)

array([1, 0, 2, 0, 0, 0, 0, 0, 2, 2])

In [211]:
model.predict(df[-10:]).argmax(axis=1)

array([2, 2, 0, 0, 2, 0, 2, 2, 2, 0])

In [212]:
cat_target[-10:].argmax(axis=1)

array([1, 2, 0, 0, 1, 2, 2, 2, 2, 0])

In [213]:
model.save('model.h5')

In [215]:
model2 = load_model('model.h5')

In [217]:
model2.predict(df[:10]).argmax(axis=1)

array([2, 0, 2, 0, 0, 0, 0, 0, 2, 0])